### ISSUE TITLE
Tried on debian11

### ISSUE THREAD

**Issue by staticdev** [lukasic/ansible-role-mariadb#1]
It fails at:

TASK [lukasic.mariadb : Install pymysql] ***************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "No package matching 'python-pymysql' is available"}

**Comment by staticdev** [comment]
I works with python3-pymysql on Debian.

**Comment by lukasic** [comment]
Fixed.
